import { RecipientConfig } from '@/types';

export const RECIPIENTS: Record<string, RecipientConfig> = {
  kiyomi: {
    slug: 'kiyomi',
    name: 'Kiyomi',
    metaTitle: 'Un pequeño jardín para Kiyomi 💛',
    metaDescription: 'Hay algunas flores que estaban esperando por ti.',
    intro: {
      salutation: 'Kiyomi…',
      subtext: 'Encontré algo que era para ti.',
      callToAction: 'Tócala 🌼',
    },
    chapter1: {
      chapterTag: 'Capítulo I',
      title: 'Una flor por cada pequeña cosa',
      instruction: 'Toca las flores cerradas para hacerlas florecer.',
      completedPrompt: 'El jardín ha comenzado a despertar...',
      flowers: [
        {
          id: 'flower-1',
          number: 1,
          shortLabel: 'Dulzura',
          note: 'Por lo dulce que eres. 💛',
          petalColor: '#FBBF24',
          centerColor: '#78350F',
          stemHeight: 120,
          scale: 1.05,
          rotation: -4,
          swayDelay: 0,
          position: { x: 18, y: 56 },
          type: 'sunflower',
        },
        {
          id: 'flower-2',
          number: 2,
          shortLabel: 'Tigger & Luneta',
          note: 'Por todas las historias de Tigger y Luneta que todavía me debes jsjs.',
          petalColor: '#F59E0B',
          centerColor: '#451A03',
          stemHeight: 105,
          scale: 0.95,
          rotation: 3,
          swayDelay: 0.8,
          position: { x: 42, y: 64 },
          type: 'daisy',
        },
        {
          id: 'flower-3',
          number: 3,
          shortLabel: 'Mikey',
          note: 'Por enseñarme de Mikey y dejarme conocer poquito a poquito tu mundo ❤️',
          petalColor: '#FCD34D',
          centerColor: '#92400E',
          stemHeight: 135,
          scale: 1.1,
          rotation: -2,
          swayDelay: 1.4,
          position: { x: 74, y: 52 },
          type: 'sunflower',
        },
        {
          id: 'flower-4',
          number: 4,
          shortLabel: 'Minecraft',
          note: 'Por aceptar que algún día te voy a enseñar Minecraft :3',
          petalColor: '#FDE047',
          centerColor: '#713F12',
          stemHeight: 110,
          scale: 0.98,
          rotation: 5,
          swayDelay: 0.4,
          position: { x: 26, y: 32 },
          type: 'wildflower',
        },
        {
          id: 'flower-5',
          number: 5,
          shortLabel: 'Aventuras',
          note: 'Por esas historias de lugares abandonados, haciendas y aventuras que todavía quiero escucharte contar.',
          petalColor: '#FBBF24',
          centerColor: '#854D0E',
          stemHeight: 125,
          scale: 1.02,
          rotation: -5,
          swayDelay: 1.1,
          position: { x: 62, y: 36 },
          type: 'tulip',
        },
        {
          id: 'flower-6',
          number: 6,
          shortLabel: 'Para ti',
          note: 'Y simplemente porque hoy una chica bonita merece sus flores amarillas.',
          petalColor: '#FEF08A',
          centerColor: '#B45309',
          stemHeight: 140,
          scale: 1.15,
          rotation: 1,
          swayDelay: 1.7,
          position: { x: 48, y: 16 },
          type: 'sunflower',
        },
      ],
    },
    chapter2: {
      chapterTag: 'Capítulo II',
      title: 'Pequeños secretos',
      instruction: 'Los jardines también guardan secretos. Explora entre las hojas.',
      counterLabel: 'secretos encontrados',
      completedPrompt: 'Has descubierto todos los secretos escondidos...',
      easterEggs: [
        {
          id: 'mikey',
          title: 'Modo Mikey Activado',
          badge: 'MODO MIKEY ACTIVADO 🏍️⚡',
          hint: 'Un destello dorado sobre dos ruedas...',
          messages: [
            'MODO MIKEY ACTIVADO',
            'Bonus especial para mi experta personal en Mikey.',
            'Todavía me debes todas esas teorías del fandom 👀',
            'Prometo intentar no perderme cuando me expliques todo jsjs.',
          ],
          accentColor: '#F59E0B',
          iconType: 'bike',
          position: { x: 80, y: 68 },
        },
        {
          id: 'tigger',
          title: 'Huella de Tigger',
          badge: 'TIGGER ESTUVO AQUÍ 🐾',
          hint: 'Algo suave que pasó corriendo entre las flores...',
          messages: [
            'Tigger estuvo aquí.',
            'Probablemente se peleó con una de las flores…',
            '…y luego huyó despavorido jsjs 🐾',
          ],
          accentColor: '#EA580C',
          iconType: 'paw',
          position: { x: 16, y: 70 },
        },
        {
          id: 'luneta',
          title: 'Luneta de Yogurt',
          badge: 'AVISTAMIENTO DE LUNETA 🐱✨',
          hint: 'Unos ojitos curiosos que se asoman de vez en cuando...',
          messages: [
            '¡Encontraste a Luneta de Yogurt!',
            'Milagro, aceptó aparecer frente a la cámara jsjs.',
            'Una aparición digna de foto inédita 📸',
          ],
          accentColor: '#D97706',
          iconType: 'cat',
          position: { x: 72, y: 22 },
        },
        {
          id: 'dark-romance',
          title: 'Dark Romance',
          badge: 'CAPÍTULO SECRETO 🖤📖',
          hint: 'Un pequeño tomo encuadernado en terciopelo...',
          messages: [
            'Dark Romance 🖤',
            'Esto también lo anoté 👀',
            'Para la lectora con gustos literarios interesantes y misteriosos.',
          ],
          accentColor: '#1F1B17',
          iconType: 'book',
          position: { x: 22, y: 25 },
        },
        {
          id: 'chocolate',
          title: 'Una Debilidad Dulce',
          badge: 'DEBILIDAD CONFIRMADA 🍫',
          hint: 'Un envoltorio diminuto con brillo dorado...',
          messages: [
            'También anoté otra debilidad…',
            'Chocolate 🍫',
            'Información peligrosamente útil jsjs.',
          ],
          accentColor: '#78350F',
          iconType: 'chocolate',
          position: { x: 48, y: 78 },
        },
      ],
    },
    chapter3: {
      chapterTag: 'Capítulo III',
      title: 'Un mundo que todavía no conoces',
      subtitle: 'Hay otro mundo que todavía quiero enseñarte.',
      blockInstruction: 'Toca el bloque de tierra con flor para iniciar la aventura',
      pixelBadge: 'PIXEL ADVENTURE ⛏️💛',
      messages: [
        'Algún día jugamos juntos.',
        'Empezamos tranquilitos…',
        'yo te enseño todo desde cero…',
        'y prometo intentar que no mueras la primera noche jsjs ❤️',
        'También tengo demasiadas historias de Minecraft que todavía quiero contarte.',
      ],
    },
    chapter4: {
      chapterTag: 'Capítulo IV',
      bouquetTitle: 'Tu ramo de flores amarillas',
      staggeredLines: [
        'Estas no son de verdad…',
        '…pero sí son solamente tuyas. 💛',
        'Con todo el cariño del mundo,',
        'aquí están tus flores amarillas',
        'por bonita hoy.',
      ],
      highlightLine: 'por bonita hoy.',
      signature: '— Diego',
      dateText: '21 · 09 · 2026',
      epiloguePrompt: 'Antes de irte… 🌼',
      epilogueMessages: [
        'Todavía quedan muchas cosas tuyas que quiero conocer.',
        'Así que este jardín todavía tiene espacio para más flores :)',
      ],
      finalFarewell: 'Fin… por ahora. 🌼',
    },
    postcard: {
      header: 'Tus flores amarillas 💛',
      forText: 'Kiyomi',
      date: '21 · 09 · 2026',
      dedication: 'Estas no son de verdad, pero sí son solamente tuyas.',
      author: '— Diego',
    },
  },
};

export function getRecipientConfig(slug?: string): RecipientConfig {
  const normalized = (slug || 'kiyomi').toLowerCase().trim();
  return RECIPIENTS[normalized] || RECIPIENTS.kiyomi;
}
